# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sharemytutoring-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DATABASEHOST: 
    Type: String
    Default: sharemytutoring.cfw1z3f57fsu.eu-west-2.rds.amazonaws.com

  DATABASEUSER: 
    Type: String
    Default: Admin

  DATABASEPASSWORD:
    Type: String
    Default: Sybase01!

  DATABASENAME: 
    Type: String
    Default: sharemytutoring

  DATABASEPORT:
    Type: String
    Default: 3306

  JWTTUTORSECRET:
    Type: String
    Default: bestTutoringSite

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 128
    Timeout: 100
    VpcConfig:
      SecurityGroupIds:
        - sg-00634fc3a409d8b49
      SubnetIds:
        - subnet-0552fc6f5cdaf111d
    Environment:
      Variables:
        DB_HOST: !Ref DATABASEHOST
        DB_USER: !Ref DATABASEUSER
        DB_PASSWORD: !Ref DATABASEPASSWORD
        DB_DATABASE: !Ref DATABASENAME
        DB_PORT: !Ref DATABASEPORT
        JWT_SECRET: !Ref JWTTUTORSECRET

  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # HelloApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: Prod
  #     Cors: "'http://127.0.0.1:3006/'"
      # AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST'"

  #
  # Authentication - This section caters for the users login in and the validation of registered accounts.
  #

  # userLogin
  # userLogin:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: userLogin
  #     Handler: src/handlers/authenticate/user-login.userLogin
  #     Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
  #     Description: User login - returns JWT token if successful and errors if unsuccessful.

  #     Events:
  #       ShareMyTutoringApi:
  #         Type: Api
  #         Properties:
  #           Path: /login
  #           Method: ANY

  # authenticate
  # validateEmailAccount:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: validateEmailAccount
  #     Handler: src/handlers/authenticate/validate-account.validateEmailAccount
  #     Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
  #     Description: validates registered accounts via email.

  #     Events:
  #       ShareMyTutoringApi:
  #         Type: Api
  #         Properties:
  #           Path: /validate-email
  #           Method: ANY

  #
  # Create Tutors
  #
  tutorMaintenance:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tutorMaintenance
      Handler: tutor.tutorHandler
      CodeUri: src/handlers/tutor
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the tutor creation, updating, deleting and retrieval.
      Layers:
      - arn:aws:lambda:eu-west-2:216211142709:layer:smt-common:11
      - arn:aws:lambda:eu-west-2:216211142709:layer:smt-tutor:7

      Events:
        ShareMyTutoringApi:
          Type: Api
          Properties:
            Path: /tutor
            Method: ANY

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

